// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: extraction_service.proto

package com.example.grpc.scraper.proto;

/**
 * Protobuf type {@code com.example.grpc.scraper.proto.ExtractionRequest}
 */
public final class ExtractionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.grpc.scraper.proto.ExtractionRequest)
    ExtractionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExtractionRequest.newBuilder() to construct.
  private ExtractionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExtractionRequest() {
    company_ = "";
    paramJson_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExtractionRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ExtractionRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            orgId_ = input.readInt64();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            company_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            paramJson_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ExtractionServiceOuterClass.internal_static_com_example_grpc_scraper_proto_ExtractionRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ExtractionServiceOuterClass.internal_static_com_example_grpc_scraper_proto_ExtractionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ExtractionRequest.class, ExtractionRequest.Builder.class);
  }

  public static final int ORGID_FIELD_NUMBER = 1;
  private long orgId_;
  /**
   * <code>int64 orgId = 1;</code>
   * @return The orgId.
   */
  @Override
  public long getOrgId() {
    return orgId_;
  }

  public static final int COMPANY_FIELD_NUMBER = 2;
  private volatile Object company_;
  /**
   * <code>string company = 2;</code>
   * @return The company.
   */
  @Override
  public String getCompany() {
    Object ref = company_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      company_ = s;
      return s;
    }
  }
  /**
   * <code>string company = 2;</code>
   * @return The bytes for company.
   */
  @Override
  public com.google.protobuf.ByteString
      getCompanyBytes() {
    Object ref = company_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      company_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARAMJSON_FIELD_NUMBER = 3;
  private volatile Object paramJson_;
  /**
   * <code>string paramJson = 3;</code>
   * @return The paramJson.
   */
  @Override
  public String getParamJson() {
    Object ref = paramJson_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      paramJson_ = s;
      return s;
    }
  }
  /**
   * <code>string paramJson = 3;</code>
   * @return The bytes for paramJson.
   */
  @Override
  public com.google.protobuf.ByteString
      getParamJsonBytes() {
    Object ref = paramJson_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      paramJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (orgId_ != 0L) {
      output.writeInt64(1, orgId_);
    }
    if (!getCompanyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, company_);
    }
    if (!getParamJsonBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, paramJson_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (orgId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, orgId_);
    }
    if (!getCompanyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, company_);
    }
    if (!getParamJsonBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, paramJson_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ExtractionRequest)) {
      return super.equals(obj);
    }
    ExtractionRequest other = (ExtractionRequest) obj;

    if (getOrgId()
        != other.getOrgId()) return false;
    if (!getCompany()
        .equals(other.getCompany())) return false;
    if (!getParamJson()
        .equals(other.getParamJson())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ORGID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOrgId());
    hash = (37 * hash) + COMPANY_FIELD_NUMBER;
    hash = (53 * hash) + getCompany().hashCode();
    hash = (37 * hash) + PARAMJSON_FIELD_NUMBER;
    hash = (53 * hash) + getParamJson().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ExtractionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExtractionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExtractionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExtractionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExtractionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExtractionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExtractionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ExtractionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ExtractionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ExtractionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ExtractionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ExtractionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ExtractionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.grpc.scraper.proto.ExtractionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.grpc.scraper.proto.ExtractionRequest)
      ExtractionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ExtractionServiceOuterClass.internal_static_com_example_grpc_scraper_proto_ExtractionRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ExtractionServiceOuterClass.internal_static_com_example_grpc_scraper_proto_ExtractionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ExtractionRequest.class, ExtractionRequest.Builder.class);
    }

    // Construct using com.example.grpc.scraper.proto.ExtractionRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      orgId_ = 0L;

      company_ = "";

      paramJson_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ExtractionServiceOuterClass.internal_static_com_example_grpc_scraper_proto_ExtractionRequest_descriptor;
    }

    @Override
    public ExtractionRequest getDefaultInstanceForType() {
      return ExtractionRequest.getDefaultInstance();
    }

    @Override
    public ExtractionRequest build() {
      ExtractionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ExtractionRequest buildPartial() {
      ExtractionRequest result = new ExtractionRequest(this);
      result.orgId_ = orgId_;
      result.company_ = company_;
      result.paramJson_ = paramJson_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ExtractionRequest) {
        return mergeFrom((ExtractionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ExtractionRequest other) {
      if (other == ExtractionRequest.getDefaultInstance()) return this;
      if (other.getOrgId() != 0L) {
        setOrgId(other.getOrgId());
      }
      if (!other.getCompany().isEmpty()) {
        company_ = other.company_;
        onChanged();
      }
      if (!other.getParamJson().isEmpty()) {
        paramJson_ = other.paramJson_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ExtractionRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ExtractionRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long orgId_ ;
    /**
     * <code>int64 orgId = 1;</code>
     * @return The orgId.
     */
    @Override
    public long getOrgId() {
      return orgId_;
    }
    /**
     * <code>int64 orgId = 1;</code>
     * @param value The orgId to set.
     * @return This builder for chaining.
     */
    public Builder setOrgId(long value) {

      orgId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 orgId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrgId() {

      orgId_ = 0L;
      onChanged();
      return this;
    }

    private Object company_ = "";
    /**
     * <code>string company = 2;</code>
     * @return The company.
     */
    public String getCompany() {
      Object ref = company_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        company_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string company = 2;</code>
     * @return The bytes for company.
     */
    public com.google.protobuf.ByteString
        getCompanyBytes() {
      Object ref = company_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        company_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string company = 2;</code>
     * @param value The company to set.
     * @return This builder for chaining.
     */
    public Builder setCompany(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      company_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string company = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompany() {

      company_ = getDefaultInstance().getCompany();
      onChanged();
      return this;
    }
    /**
     * <code>string company = 2;</code>
     * @param value The bytes for company to set.
     * @return This builder for chaining.
     */
    public Builder setCompanyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      company_ = value;
      onChanged();
      return this;
    }

    private Object paramJson_ = "";
    /**
     * <code>string paramJson = 3;</code>
     * @return The paramJson.
     */
    public String getParamJson() {
      Object ref = paramJson_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        paramJson_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string paramJson = 3;</code>
     * @return The bytes for paramJson.
     */
    public com.google.protobuf.ByteString
        getParamJsonBytes() {
      Object ref = paramJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        paramJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string paramJson = 3;</code>
     * @param value The paramJson to set.
     * @return This builder for chaining.
     */
    public Builder setParamJson(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      paramJson_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string paramJson = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearParamJson() {

      paramJson_ = getDefaultInstance().getParamJson();
      onChanged();
      return this;
    }
    /**
     * <code>string paramJson = 3;</code>
     * @param value The bytes for paramJson to set.
     * @return This builder for chaining.
     */
    public Builder setParamJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      paramJson_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.grpc.scraper.proto.ExtractionRequest)
  }

  // @@protoc_insertion_point(class_scope:com.example.grpc.scraper.proto.ExtractionRequest)
  private static final ExtractionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ExtractionRequest();
  }

  public static ExtractionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExtractionRequest>
      PARSER = new com.google.protobuf.AbstractParser<ExtractionRequest>() {
    @Override
    public ExtractionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ExtractionRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExtractionRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ExtractionRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public ExtractionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

