// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: extraction_service.proto

package com.example.grpc.scraper.proto;

public interface ExtractionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.scraper.proto.ExtractionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 orgId = 1;</code>
   * @return The orgId.
   */
  long getOrgId();

  /**
   * <code>string company = 2;</code>
   * @return The company.
   */
  String getCompany();
  /**
   * <code>string company = 2;</code>
   * @return The bytes for company.
   */
  com.google.protobuf.ByteString
      getCompanyBytes();

  /**
   * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
   */
  java.util.List<JobDetails>
      getJobDetailsList();
  /**
   * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
   */
  JobDetails getJobDetails(int index);
  /**
   * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
   */
  int getJobDetailsCount();
  /**
   * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
   */
  java.util.List<? extends JobDetailsOrBuilder>
      getJobDetailsOrBuilderList();
  /**
   * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
   */
  JobDetailsOrBuilder getJobDetailsOrBuilder(
          int index);
}
