// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: extraction_service.proto

package com.example.grpc.scraper.proto;

public interface ExtractionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.scraper.proto.ExtractionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 orgId = 1;</code>
   * @return The orgId.
   */
  long getOrgId();

  /**
   * <code>string company = 2;</code>
   * @return The company.
   */
  String getCompany();
  /**
   * <code>string company = 2;</code>
   * @return The bytes for company.
   */
  com.google.protobuf.ByteString
      getCompanyBytes();

  /**
   * <code>string paramJson = 3;</code>
   * @return The paramJson.
   */
  String getParamJson();
  /**
   * <code>string paramJson = 3;</code>
   * @return The bytes for paramJson.
   */
  com.google.protobuf.ByteString
      getParamJsonBytes();
}
