// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: extraction_service.proto

package com.example.grpc.scraper.proto;

/**
 * Protobuf type {@code com.example.grpc.scraper.proto.ExtractionResponse}
 */
public final class ExtractionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.grpc.scraper.proto.ExtractionResponse)
    ExtractionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExtractionResponse.newBuilder() to construct.
  private ExtractionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExtractionResponse() {
    company_ = "";
    jobDetails_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExtractionResponse();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ExtractionResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            orgId_ = input.readInt64();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            company_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              jobDetails_ = new java.util.ArrayList<JobDetails>();
              mutable_bitField0_ |= 0x00000001;
            }
            jobDetails_.add(
                input.readMessage(JobDetails.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        jobDetails_ = java.util.Collections.unmodifiableList(jobDetails_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ExtractionServiceOuterClass.internal_static_com_example_grpc_scraper_proto_ExtractionResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ExtractionServiceOuterClass.internal_static_com_example_grpc_scraper_proto_ExtractionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ExtractionResponse.class, ExtractionResponse.Builder.class);
  }

  public static final int ORGID_FIELD_NUMBER = 1;
  private long orgId_;
  /**
   * <code>int64 orgId = 1;</code>
   * @return The orgId.
   */
  @Override
  public long getOrgId() {
    return orgId_;
  }

  public static final int COMPANY_FIELD_NUMBER = 2;
  private volatile Object company_;
  /**
   * <code>string company = 2;</code>
   * @return The company.
   */
  @Override
  public String getCompany() {
    Object ref = company_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      company_ = s;
      return s;
    }
  }
  /**
   * <code>string company = 2;</code>
   * @return The bytes for company.
   */
  @Override
  public com.google.protobuf.ByteString
      getCompanyBytes() {
    Object ref = company_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      company_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JOBDETAILS_FIELD_NUMBER = 3;
  private java.util.List<JobDetails> jobDetails_;
  /**
   * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
   */
  @Override
  public java.util.List<JobDetails> getJobDetailsList() {
    return jobDetails_;
  }
  /**
   * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
   */
  @Override
  public java.util.List<? extends JobDetailsOrBuilder>
      getJobDetailsOrBuilderList() {
    return jobDetails_;
  }
  /**
   * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
   */
  @Override
  public int getJobDetailsCount() {
    return jobDetails_.size();
  }
  /**
   * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
   */
  @Override
  public JobDetails getJobDetails(int index) {
    return jobDetails_.get(index);
  }
  /**
   * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
   */
  @Override
  public JobDetailsOrBuilder getJobDetailsOrBuilder(
      int index) {
    return jobDetails_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (orgId_ != 0L) {
      output.writeInt64(1, orgId_);
    }
    if (!getCompanyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, company_);
    }
    for (int i = 0; i < jobDetails_.size(); i++) {
      output.writeMessage(3, jobDetails_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (orgId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, orgId_);
    }
    if (!getCompanyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, company_);
    }
    for (int i = 0; i < jobDetails_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, jobDetails_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ExtractionResponse)) {
      return super.equals(obj);
    }
    ExtractionResponse other = (ExtractionResponse) obj;

    if (getOrgId()
        != other.getOrgId()) return false;
    if (!getCompany()
        .equals(other.getCompany())) return false;
    if (!getJobDetailsList()
        .equals(other.getJobDetailsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ORGID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getOrgId());
    hash = (37 * hash) + COMPANY_FIELD_NUMBER;
    hash = (53 * hash) + getCompany().hashCode();
    if (getJobDetailsCount() > 0) {
      hash = (37 * hash) + JOBDETAILS_FIELD_NUMBER;
      hash = (53 * hash) + getJobDetailsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ExtractionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExtractionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExtractionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExtractionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExtractionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExtractionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExtractionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ExtractionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ExtractionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ExtractionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ExtractionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ExtractionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ExtractionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.grpc.scraper.proto.ExtractionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.grpc.scraper.proto.ExtractionResponse)
      ExtractionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ExtractionServiceOuterClass.internal_static_com_example_grpc_scraper_proto_ExtractionResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ExtractionServiceOuterClass.internal_static_com_example_grpc_scraper_proto_ExtractionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ExtractionResponse.class, ExtractionResponse.Builder.class);
    }

    // Construct using com.example.grpc.scraper.proto.ExtractionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getJobDetailsFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      orgId_ = 0L;

      company_ = "";

      if (jobDetailsBuilder_ == null) {
        jobDetails_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        jobDetailsBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ExtractionServiceOuterClass.internal_static_com_example_grpc_scraper_proto_ExtractionResponse_descriptor;
    }

    @Override
    public ExtractionResponse getDefaultInstanceForType() {
      return ExtractionResponse.getDefaultInstance();
    }

    @Override
    public ExtractionResponse build() {
      ExtractionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ExtractionResponse buildPartial() {
      ExtractionResponse result = new ExtractionResponse(this);
      int from_bitField0_ = bitField0_;
      result.orgId_ = orgId_;
      result.company_ = company_;
      if (jobDetailsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          jobDetails_ = java.util.Collections.unmodifiableList(jobDetails_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.jobDetails_ = jobDetails_;
      } else {
        result.jobDetails_ = jobDetailsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ExtractionResponse) {
        return mergeFrom((ExtractionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ExtractionResponse other) {
      if (other == ExtractionResponse.getDefaultInstance()) return this;
      if (other.getOrgId() != 0L) {
        setOrgId(other.getOrgId());
      }
      if (!other.getCompany().isEmpty()) {
        company_ = other.company_;
        onChanged();
      }
      if (jobDetailsBuilder_ == null) {
        if (!other.jobDetails_.isEmpty()) {
          if (jobDetails_.isEmpty()) {
            jobDetails_ = other.jobDetails_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureJobDetailsIsMutable();
            jobDetails_.addAll(other.jobDetails_);
          }
          onChanged();
        }
      } else {
        if (!other.jobDetails_.isEmpty()) {
          if (jobDetailsBuilder_.isEmpty()) {
            jobDetailsBuilder_.dispose();
            jobDetailsBuilder_ = null;
            jobDetails_ = other.jobDetails_;
            bitField0_ = (bitField0_ & ~0x00000001);
            jobDetailsBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getJobDetailsFieldBuilder() : null;
          } else {
            jobDetailsBuilder_.addAllMessages(other.jobDetails_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ExtractionResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ExtractionResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long orgId_ ;
    /**
     * <code>int64 orgId = 1;</code>
     * @return The orgId.
     */
    @Override
    public long getOrgId() {
      return orgId_;
    }
    /**
     * <code>int64 orgId = 1;</code>
     * @param value The orgId to set.
     * @return This builder for chaining.
     */
    public Builder setOrgId(long value) {

      orgId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 orgId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrgId() {

      orgId_ = 0L;
      onChanged();
      return this;
    }

    private Object company_ = "";
    /**
     * <code>string company = 2;</code>
     * @return The company.
     */
    public String getCompany() {
      Object ref = company_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        company_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string company = 2;</code>
     * @return The bytes for company.
     */
    public com.google.protobuf.ByteString
        getCompanyBytes() {
      Object ref = company_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        company_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string company = 2;</code>
     * @param value The company to set.
     * @return This builder for chaining.
     */
    public Builder setCompany(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      company_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string company = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompany() {

      company_ = getDefaultInstance().getCompany();
      onChanged();
      return this;
    }
    /**
     * <code>string company = 2;</code>
     * @param value The bytes for company to set.
     * @return This builder for chaining.
     */
    public Builder setCompanyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      company_ = value;
      onChanged();
      return this;
    }

    private java.util.List<JobDetails> jobDetails_ =
      java.util.Collections.emptyList();
    private void ensureJobDetailsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        jobDetails_ = new java.util.ArrayList<JobDetails>(jobDetails_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        JobDetails, JobDetails.Builder, JobDetailsOrBuilder> jobDetailsBuilder_;

    /**
     * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
     */
    public java.util.List<JobDetails> getJobDetailsList() {
      if (jobDetailsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(jobDetails_);
      } else {
        return jobDetailsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
     */
    public int getJobDetailsCount() {
      if (jobDetailsBuilder_ == null) {
        return jobDetails_.size();
      } else {
        return jobDetailsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
     */
    public JobDetails getJobDetails(int index) {
      if (jobDetailsBuilder_ == null) {
        return jobDetails_.get(index);
      } else {
        return jobDetailsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
     */
    public Builder setJobDetails(
        int index, JobDetails value) {
      if (jobDetailsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobDetailsIsMutable();
        jobDetails_.set(index, value);
        onChanged();
      } else {
        jobDetailsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
     */
    public Builder setJobDetails(
        int index, JobDetails.Builder builderForValue) {
      if (jobDetailsBuilder_ == null) {
        ensureJobDetailsIsMutable();
        jobDetails_.set(index, builderForValue.build());
        onChanged();
      } else {
        jobDetailsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
     */
    public Builder addJobDetails(JobDetails value) {
      if (jobDetailsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobDetailsIsMutable();
        jobDetails_.add(value);
        onChanged();
      } else {
        jobDetailsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
     */
    public Builder addJobDetails(
        int index, JobDetails value) {
      if (jobDetailsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobDetailsIsMutable();
        jobDetails_.add(index, value);
        onChanged();
      } else {
        jobDetailsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
     */
    public Builder addJobDetails(
        JobDetails.Builder builderForValue) {
      if (jobDetailsBuilder_ == null) {
        ensureJobDetailsIsMutable();
        jobDetails_.add(builderForValue.build());
        onChanged();
      } else {
        jobDetailsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
     */
    public Builder addJobDetails(
        int index, JobDetails.Builder builderForValue) {
      if (jobDetailsBuilder_ == null) {
        ensureJobDetailsIsMutable();
        jobDetails_.add(index, builderForValue.build());
        onChanged();
      } else {
        jobDetailsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
     */
    public Builder addAllJobDetails(
        Iterable<? extends JobDetails> values) {
      if (jobDetailsBuilder_ == null) {
        ensureJobDetailsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, jobDetails_);
        onChanged();
      } else {
        jobDetailsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
     */
    public Builder clearJobDetails() {
      if (jobDetailsBuilder_ == null) {
        jobDetails_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        jobDetailsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
     */
    public Builder removeJobDetails(int index) {
      if (jobDetailsBuilder_ == null) {
        ensureJobDetailsIsMutable();
        jobDetails_.remove(index);
        onChanged();
      } else {
        jobDetailsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
     */
    public JobDetails.Builder getJobDetailsBuilder(
        int index) {
      return getJobDetailsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
     */
    public JobDetailsOrBuilder getJobDetailsOrBuilder(
        int index) {
      if (jobDetailsBuilder_ == null) {
        return jobDetails_.get(index);  } else {
        return jobDetailsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
     */
    public java.util.List<? extends JobDetailsOrBuilder>
         getJobDetailsOrBuilderList() {
      if (jobDetailsBuilder_ != null) {
        return jobDetailsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(jobDetails_);
      }
    }
    /**
     * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
     */
    public JobDetails.Builder addJobDetailsBuilder() {
      return getJobDetailsFieldBuilder().addBuilder(
          JobDetails.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
     */
    public JobDetails.Builder addJobDetailsBuilder(
        int index) {
      return getJobDetailsFieldBuilder().addBuilder(
          index, JobDetails.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.grpc.scraper.proto.JobDetails jobDetails = 3;</code>
     */
    public java.util.List<JobDetails.Builder>
         getJobDetailsBuilderList() {
      return getJobDetailsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        JobDetails, JobDetails.Builder, JobDetailsOrBuilder>
        getJobDetailsFieldBuilder() {
      if (jobDetailsBuilder_ == null) {
        jobDetailsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            JobDetails, JobDetails.Builder, JobDetailsOrBuilder>(
                jobDetails_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        jobDetails_ = null;
      }
      return jobDetailsBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.grpc.scraper.proto.ExtractionResponse)
  }

  // @@protoc_insertion_point(class_scope:com.example.grpc.scraper.proto.ExtractionResponse)
  private static final ExtractionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ExtractionResponse();
  }

  public static ExtractionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExtractionResponse>
      PARSER = new com.google.protobuf.AbstractParser<ExtractionResponse>() {
    @Override
    public ExtractionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ExtractionResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExtractionResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ExtractionResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public ExtractionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

