// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: extraction_service.proto

package com.example.grpc.scraper.proto;

public interface JobDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.scraper.proto.JobDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string jobTitle = 1;</code>
   * @return The jobTitle.
   */
  String getJobTitle();
  /**
   * <code>string jobTitle = 1;</code>
   * @return The bytes for jobTitle.
   */
  com.google.protobuf.ByteString
      getJobTitleBytes();
}
